// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIReady() {
  return window['go']['binding']['API']['AIReady']();
}

export function AcknowledgeChangeSummary() {
  return window['go']['binding']['API']['AcknowledgeChangeSummary']();
}

export function AddExistingProject(arg1) {
  return window['go']['binding']['API']['AddExistingProject'](arg1);
}

export function AddMember(arg1) {
  return window['go']['binding']['API']['AddMember'](arg1);
}

export function AddPerspective(arg1) {
  return window['go']['binding']['API']['AddPerspective'](arg1);
}

export function AddStakeholder(arg1) {
  return window['go']['binding']['API']['AddStakeholder'](arg1);
}

export function AgreeRequirement(arg1) {
  return window['go']['binding']['API']['AgreeRequirement'](arg1);
}

export function AnalyzeImport(arg1, arg2) {
  return window['go']['binding']['API']['AnalyzeImport'](arg1, arg2);
}

export function AnalyzeImportedAnswers(arg1) {
  return window['go']['binding']['API']['AnalyzeImportedAnswers'](arg1);
}

export function AppInfo() {
  return window['go']['binding']['API']['AppInfo']();
}

export function ApplyUpdate() {
  return window['go']['binding']['API']['ApplyUpdate']();
}

export function ApproveDialogueCandidates(arg1, arg2) {
  return window['go']['binding']['API']['ApproveDialogueCandidates'](arg1, arg2);
}

export function ApproveImportCandidates(arg1, arg2) {
  return window['go']['binding']['API']['ApproveImportCandidates'](arg1, arg2);
}

export function ApproveImportDiff(arg1, arg2) {
  return window['go']['binding']['API']['ApproveImportDiff'](arg1, arg2);
}

export function AskNextQuestion(arg1) {
  return window['go']['binding']['API']['AskNextQuestion'](arg1);
}

export function BackupGenerations(arg1) {
  return window['go']['binding']['API']['BackupGenerations'](arg1);
}

export function BackupProject(arg1) {
  return window['go']['binding']['API']['BackupProject'](arg1);
}

export function CancelCodexSignIn() {
  return window['go']['binding']['API']['CancelCodexSignIn']();
}

export function CancelRespondAIMessage() {
  return window['go']['binding']['API']['CancelRespondAIMessage']();
}

export function CancelUpdate() {
  return window['go']['binding']['API']['CancelUpdate']();
}

export function ChangeHistory() {
  return window['go']['binding']['API']['ChangeHistory']();
}

export function ChangeMemberRole(arg1) {
  return window['go']['binding']['API']['ChangeMemberRole'](arg1);
}

export function ChangeSummary() {
  return window['go']['binding']['API']['ChangeSummary']();
}

export function CheckDocumentReservation(arg1) {
  return window['go']['binding']['API']['CheckDocumentReservation'](arg1);
}

export function CheckForUpdate() {
  return window['go']['binding']['API']['CheckForUpdate']();
}

export function CheckPhaseDocumentReservation() {
  return window['go']['binding']['API']['CheckPhaseDocumentReservation']();
}

export function CheckReservation(arg1) {
  return window['go']['binding']['API']['CheckReservation'](arg1);
}

export function CheckSyncConnection(arg1, arg2) {
  return window['go']['binding']['API']['CheckSyncConnection'](arg1, arg2);
}

export function ChooseBackupFile() {
  return window['go']['binding']['API']['ChooseBackupFile']();
}

export function ChooseFolder(arg1) {
  return window['go']['binding']['API']['ChooseFolder'](arg1);
}

export function ChooseImportDirectory() {
  return window['go']['binding']['API']['ChooseImportDirectory']();
}

export function ChooseImportFile() {
  return window['go']['binding']['API']['ChooseImportFile']();
}

export function ChooseIssueDestination(arg1) {
  return window['go']['binding']['API']['ChooseIssueDestination'](arg1);
}

export function ChooseProgressReportDestination() {
  return window['go']['binding']['API']['ChooseProgressReportDestination']();
}

export function ChooseProject(arg1) {
  return window['go']['binding']['API']['ChooseProject'](arg1);
}

export function ChooseReturnDestination() {
  return window['go']['binding']['API']['ChooseReturnDestination']();
}

export function ChooseReturnFile() {
  return window['go']['binding']['API']['ChooseReturnFile']();
}

export function ChooseUsageReportDestination() {
  return window['go']['binding']['API']['ChooseUsageReportDestination']();
}

export function ClearUsageLimit() {
  return window['go']['binding']['API']['ClearUsageLimit']();
}

export function CloneSyncProject(arg1) {
  return window['go']['binding']['API']['CloneSyncProject'](arg1);
}

export function CloseDialogueProject() {
  return window['go']['binding']['API']['CloseDialogueProject']();
}

export function CodexAccount(arg1) {
  return window['go']['binding']['API']['CodexAccount'](arg1);
}

export function CodexPlanUsage(arg1) {
  return window['go']['binding']['API']['CodexPlanUsage'](arg1);
}

export function CodexSignInState() {
  return window['go']['binding']['API']['CodexSignInState']();
}

export function CompleteSetup(arg1) {
  return window['go']['binding']['API']['CompleteSetup'](arg1);
}

export function ConfirmCheck(arg1) {
  return window['go']['binding']['API']['ConfirmCheck'](arg1);
}

export function ConfirmDocument(arg1, arg2) {
  return window['go']['binding']['API']['ConfirmDocument'](arg1, arg2);
}

export function CopyProgressReport(arg1) {
  return window['go']['binding']['API']['CopyProgressReport'](arg1);
}

export function CopyUsageReport(arg1) {
  return window['go']['binding']['API']['CopyUsageReport'](arg1);
}

export function CorrectMemberAuthorID(arg1, arg2) {
  return window['go']['binding']['API']['CorrectMemberAuthorID'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['binding']['API']['CreateProject'](arg1);
}

export function CreateSyncMergeOpenIssue(arg1) {
  return window['go']['binding']['API']['CreateSyncMergeOpenIssue'](arg1);
}

export function CurrentPermission() {
  return window['go']['binding']['API']['CurrentPermission']();
}

export function Decisions() {
  return window['go']['binding']['API']['Decisions']();
}

export function DeferUpdate() {
  return window['go']['binding']['API']['DeferUpdate']();
}

export function DeleteKey(arg1, arg2) {
  return window['go']['binding']['API']['DeleteKey'](arg1, arg2);
}

export function DeletePreview(arg1) {
  return window['go']['binding']['API']['DeletePreview'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['binding']['API']['DeleteProject'](arg1);
}

export function DeleteSyncCredential(arg1) {
  return window['go']['binding']['API']['DeleteSyncCredential'](arg1);
}

export function DiagnosticsPreview() {
  return window['go']['binding']['API']['DiagnosticsPreview']();
}

export function DialogueCompleteness() {
  return window['go']['binding']['API']['DialogueCompleteness']();
}

export function DialogueSessions() {
  return window['go']['binding']['API']['DialogueSessions']();
}

export function DialogueUtterances(arg1) {
  return window['go']['binding']['API']['DialogueUtterances'](arg1);
}

export function DisableRespondAI() {
  return window['go']['binding']['API']['DisableRespondAI']();
}

export function DocumentChapters(arg1, arg2) {
  return window['go']['binding']['API']['DocumentChapters'](arg1, arg2);
}

export function DocumentDiff(arg1, arg2, arg3) {
  return window['go']['binding']['API']['DocumentDiff'](arg1, arg2, arg3);
}

export function DocumentVersions(arg1) {
  return window['go']['binding']['API']['DocumentVersions'](arg1);
}

export function DomainPresets() {
  return window['go']['binding']['API']['DomainPresets']();
}

export function EditRequirement(arg1) {
  return window['go']['binding']['API']['EditRequirement'](arg1);
}

export function EnableRespondAI(arg1, arg2, arg3) {
  return window['go']['binding']['API']['EnableRespondAI'](arg1, arg2, arg3);
}

export function Evidence(arg1) {
  return window['go']['binding']['API']['Evidence'](arg1);
}

export function EvidenceCitations(arg1) {
  return window['go']['binding']['API']['EvidenceCitations'](arg1);
}

export function ExportDiagnostics() {
  return window['go']['binding']['API']['ExportDiagnostics']();
}

export function ExportDocuments(arg1) {
  return window['go']['binding']['API']['ExportDocuments'](arg1);
}

export function FeedbackClassificationOptions() {
  return window['go']['binding']['API']['FeedbackClassificationOptions']();
}

export function FeedbackSummary(arg1, arg2) {
  return window['go']['binding']['API']['FeedbackSummary'](arg1, arg2);
}

export function FinalizeAnswers(arg1) {
  return window['go']['binding']['API']['FinalizeAnswers'](arg1);
}

export function ForgetProject(arg1) {
  return window['go']['binding']['API']['ForgetProject'](arg1);
}

export function GenerateDocument(arg1, arg2, arg3) {
  return window['go']['binding']['API']['GenerateDocument'](arg1, arg2, arg3);
}

export function GenerateQuestionDrafts(arg1) {
  return window['go']['binding']['API']['GenerateQuestionDrafts'](arg1);
}

export function HandleOpenFile(arg1) {
  return window['go']['binding']['API']['HandleOpenFile'](arg1);
}

export function IDRangeWarnings() {
  return window['go']['binding']['API']['IDRangeWarnings']();
}

export function Impact(arg1) {
  return window['go']['binding']['API']['Impact'](arg1);
}

export function ImportClipboardText(arg1, arg2) {
  return window['go']['binding']['API']['ImportClipboardText'](arg1, arg2);
}

export function ImportContent(arg1) {
  return window['go']['binding']['API']['ImportContent'](arg1);
}

export function ImportDirectory(arg1, arg2) {
  return window['go']['binding']['API']['ImportDirectory'](arg1, arg2);
}

export function ImportFile(arg1, arg2) {
  return window['go']['binding']['API']['ImportFile'](arg1, arg2);
}

export function ImportKinds() {
  return window['go']['binding']['API']['ImportKinds']();
}

export function ImportReturnFile(arg1) {
  return window['go']['binding']['API']['ImportReturnFile'](arg1);
}

export function Imports() {
  return window['go']['binding']['API']['Imports']();
}

export function IncorporateSync(arg1) {
  return window['go']['binding']['API']['IncorporateSync'](arg1);
}

export function InterruptDialogue() {
  return window['go']['binding']['API']['InterruptDialogue']();
}

export function IntroShown() {
  return window['go']['binding']['API']['IntroShown']();
}

export function IssueQuestionnaire(arg1, arg2) {
  return window['go']['binding']['API']['IssueQuestionnaire'](arg1, arg2);
}

export function LocationWarning(arg1) {
  return window['go']['binding']['API']['LocationWarning'](arg1);
}

export function Log() {
  return window['go']['binding']['API']['Log']();
}

export function MarkIntroShown() {
  return window['go']['binding']['API']['MarkIntroShown']();
}

export function Members() {
  return window['go']['binding']['API']['Members']();
}

export function MigratableProjects() {
  return window['go']['binding']['API']['MigratableProjects']();
}

export function MigrateProject(arg1) {
  return window['go']['binding']['API']['MigrateProject'](arg1);
}

export function MissingEvidenceRecords() {
  return window['go']['binding']['API']['MissingEvidenceRecords']();
}

export function Models(arg1, arg2, arg3) {
  return window['go']['binding']['API']['Models'](arg1, arg2, arg3);
}

export function MoveToBasicDesign() {
  return window['go']['binding']['API']['MoveToBasicDesign']();
}

export function OpenDialogueProject(arg1) {
  return window['go']['binding']['API']['OpenDialogueProject'](arg1);
}

export function OpenIssues() {
  return window['go']['binding']['API']['OpenIssues']();
}

export function OpenQuestionnaireFile(arg1, arg2) {
  return window['go']['binding']['API']['OpenQuestionnaireFile'](arg1, arg2);
}

export function PaneWidths() {
  return window['go']['binding']['API']['PaneWidths']();
}

export function PendingCandidates(arg1) {
  return window['go']['binding']['API']['PendingCandidates'](arg1);
}

export function PendingImportCandidates(arg1) {
  return window['go']['binding']['API']['PendingImportCandidates'](arg1);
}

export function PendingOpenFile() {
  return window['go']['binding']['API']['PendingOpenFile']();
}

export function Perspectives() {
  return window['go']['binding']['API']['Perspectives']();
}

export function PreviewBackup(arg1) {
  return window['go']['binding']['API']['PreviewBackup'](arg1);
}

export function PreviewImportAnalysis(arg1) {
  return window['go']['binding']['API']['PreviewImportAnalysis'](arg1);
}

export function PreviewQuestionnaireIssue(arg1) {
  return window['go']['binding']['API']['PreviewQuestionnaireIssue'](arg1);
}

export function PreviewSyncPublish() {
  return window['go']['binding']['API']['PreviewSyncPublish']();
}

export function PreviousRunIncomplete() {
  return window['go']['binding']['API']['PreviousRunIncomplete']();
}

export function ProgressReport(arg1) {
  return window['go']['binding']['API']['ProgressReport'](arg1);
}

export function ProjectFolderNameFor(arg1) {
  return window['go']['binding']['API']['ProjectFolderNameFor'](arg1);
}

export function Projects() {
  return window['go']['binding']['API']['Projects']();
}

export function PublishSync(arg1) {
  return window['go']['binding']['API']['PublishSync'](arg1);
}

export function Questionnaires() {
  return window['go']['binding']['API']['Questionnaires']();
}

export function ReattachSync() {
  return window['go']['binding']['API']['ReattachSync']();
}

export function RegisterKey(arg1, arg2, arg3) {
  return window['go']['binding']['API']['RegisterKey'](arg1, arg2, arg3);
}

export function RegisterRespondAIKey(arg1, arg2, arg3) {
  return window['go']['binding']['API']['RegisterRespondAIKey'](arg1, arg2, arg3);
}

export function RegisterSyncCredential(arg1) {
  return window['go']['binding']['API']['RegisterSyncCredential'](arg1);
}

export function ReissueQuestionnaire(arg1, arg2) {
  return window['go']['binding']['API']['ReissueQuestionnaire'](arg1, arg2);
}

export function ReleaseReservation(arg1, arg2, arg3) {
  return window['go']['binding']['API']['ReleaseReservation'](arg1, arg2, arg3);
}

export function ReleaseWindowLock(arg1, arg2) {
  return window['go']['binding']['API']['ReleaseWindowLock'](arg1, arg2);
}

export function RemoveMember(arg1) {
  return window['go']['binding']['API']['RemoveMember'](arg1);
}

export function RemovePerspective(arg1) {
  return window['go']['binding']['API']['RemovePerspective'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['binding']['API']['RenameProject'](arg1, arg2);
}

export function ReopenCodexSignInPage() {
  return window['go']['binding']['API']['ReopenCodexSignInPage']();
}

export function Requirements() {
  return window['go']['binding']['API']['Requirements']();
}

export function Reservations() {
  return window['go']['binding']['API']['Reservations']();
}

export function RespondAIAnswerDraft(arg1, arg2, arg3) {
  return window['go']['binding']['API']['RespondAIAnswerDraft'](arg1, arg2, arg3);
}

export function RespondAIDialogue() {
  return window['go']['binding']['API']['RespondAIDialogue']();
}

export function RespondAIProviders() {
  return window['go']['binding']['API']['RespondAIProviders']();
}

export function RespondAIScope(arg1) {
  return window['go']['binding']['API']['RespondAIScope'](arg1);
}

export function RespondProgress() {
  return window['go']['binding']['API']['RespondProgress']();
}

export function RestartApp() {
  return window['go']['binding']['API']['RestartApp']();
}

export function RestoreBackup(arg1, arg2, arg3) {
  return window['go']['binding']['API']['RestoreBackup'](arg1, arg2, arg3);
}

export function ResumeDialogueSession(arg1) {
  return window['go']['binding']['API']['ResumeDialogueSession'](arg1);
}

export function RevertRequirement(arg1, arg2, arg3) {
  return window['go']['binding']['API']['RevertRequirement'](arg1, arg2, arg3);
}

export function Roster() {
  return window['go']['binding']['API']['Roster']();
}

export function SaveAnswer(arg1) {
  return window['go']['binding']['API']['SaveAnswer'](arg1);
}

export function SaveProgressReport(arg1, arg2) {
  return window['go']['binding']['API']['SaveProgressReport'](arg1, arg2);
}

export function SaveProviderConfig(arg1) {
  return window['go']['binding']['API']['SaveProviderConfig'](arg1);
}

export function SaveUsageReport(arg1, arg2) {
  return window['go']['binding']['API']['SaveUsageReport'](arg1, arg2);
}

export function ScaleStatus() {
  return window['go']['binding']['API']['ScaleStatus']();
}

export function ScanImportDirectory(arg1) {
  return window['go']['binding']['API']['ScanImportDirectory'](arg1);
}

export function SearchDialogueUtterances(arg1, arg2, arg3) {
  return window['go']['binding']['API']['SearchDialogueUtterances'](arg1, arg2, arg3);
}

export function SendAnswer(arg1, arg2) {
  return window['go']['binding']['API']['SendAnswer'](arg1, arg2);
}

export function SendRespondAIMessage(arg1) {
  return window['go']['binding']['API']['SendRespondAIMessage'](arg1);
}

export function SetAITimeouts(arg1, arg2) {
  return window['go']['binding']['API']['SetAITimeouts'](arg1, arg2);
}

export function SetDisplayName(arg1) {
  return window['go']['binding']['API']['SetDisplayName'](arg1);
}

export function SetDomainPresets(arg1, arg2) {
  return window['go']['binding']['API']['SetDomainPresets'](arg1, arg2);
}

export function SetFeedbackClassification(arg1, arg2) {
  return window['go']['binding']['API']['SetFeedbackClassification'](arg1, arg2);
}

export function SetPaneWidths(arg1, arg2) {
  return window['go']['binding']['API']['SetPaneWidths'](arg1, arg2);
}

export function SetSyncRemote(arg1) {
  return window['go']['binding']['API']['SetSyncRemote'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['binding']['API']['SetTheme'](arg1);
}

export function SetUsageLimit(arg1) {
  return window['go']['binding']['API']['SetUsageLimit'](arg1);
}

export function SettingsView() {
  return window['go']['binding']['API']['SettingsView']();
}

export function SetupState() {
  return window['go']['binding']['API']['SetupState']();
}

export function SignOutCodex(arg1) {
  return window['go']['binding']['API']['SignOutCodex'](arg1);
}

export function SignOutRespondAI() {
  return window['go']['binding']['API']['SignOutRespondAI']();
}

export function StartCodexSignIn(arg1) {
  return window['go']['binding']['API']['StartCodexSignIn'](arg1);
}

export function StartDialogueSession() {
  return window['go']['binding']['API']['StartDialogueSession']();
}

export function StartRespondAISignIn(arg1) {
  return window['go']['binding']['API']['StartRespondAISignIn'](arg1);
}

export function StartWork(arg1, arg2, arg3) {
  return window['go']['binding']['API']['StartWork'](arg1, arg2, arg3);
}

export function StartupMode() {
  return window['go']['binding']['API']['StartupMode']();
}

export function SuspendDialogue(arg1) {
  return window['go']['binding']['API']['SuspendDialogue'](arg1);
}

export function SyncCredentialView(arg1) {
  return window['go']['binding']['API']['SyncCredentialView'](arg1);
}

export function SyncKindOptions() {
  return window['go']['binding']['API']['SyncKindOptions']();
}

export function SyncLog() {
  return window['go']['binding']['API']['SyncLog']();
}

export function SyncMergeOptions() {
  return window['go']['binding']['API']['SyncMergeOptions']();
}

export function SyncRemote() {
  return window['go']['binding']['API']['SyncRemote']();
}

export function SyncStatus() {
  return window['go']['binding']['API']['SyncStatus']();
}

export function TakeOverOwner(arg1) {
  return window['go']['binding']['API']['TakeOverOwner'](arg1);
}

export function Theme() {
  return window['go']['binding']['API']['Theme']();
}

export function TokenUsage(arg1) {
  return window['go']['binding']['API']['TokenUsage'](arg1);
}

export function UpdatePerspective(arg1) {
  return window['go']['binding']['API']['UpdatePerspective'](arg1);
}

export function UpdateStakeholder(arg1) {
  return window['go']['binding']['API']['UpdateStakeholder'](arg1);
}

export function UpdateState() {
  return window['go']['binding']['API']['UpdateState']();
}

export function UsageDashboard(arg1) {
  return window['go']['binding']['API']['UsageDashboard'](arg1);
}

export function UsageStatusNow() {
  return window['go']['binding']['API']['UsageStatusNow']();
}

export function ValidateReturnFile(arg1) {
  return window['go']['binding']['API']['ValidateReturnFile'](arg1);
}

export function VerifyDocument(arg1, arg2) {
  return window['go']['binding']['API']['VerifyDocument'](arg1, arg2);
}

export function VerifyKey(arg1, arg2) {
  return window['go']['binding']['API']['VerifyKey'](arg1, arg2);
}

export function WindowLocks() {
  return window['go']['binding']['API']['WindowLocks']();
}

export function WorkModeOptions() {
  return window['go']['binding']['API']['WorkModeOptions']();
}

export function WorkflowGuide() {
  return window['go']['binding']['API']['WorkflowGuide']();
}
