// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding} from '../models';
import {dialogue} from '../models';
import {applog} from '../models';
import {docgen} from '../models';
import {projectstore} from '../models';
import {importer} from '../models';
import {exchange} from '../models';

export function AIReady():Promise<binding.SettingsView>;

export function AcknowledgeChangeSummary():Promise<void>;

export function AddExistingProject(arg1:string):Promise<binding.ProjectSummary>;

export function AddMember(arg1:binding.MemberRequest):Promise<binding.MemberView>;

export function AddPerspective(arg1:binding.PerspectiveRequest):Promise<binding.PerspectiveView>;

export function AddStakeholder(arg1:binding.StakeholderRequest):Promise<binding.StakeholderView>;

export function AgreeRequirement(arg1:string):Promise<binding.RequirementView>;

export function AnalyzeImport(arg1:string,arg2:boolean):Promise<dialogue.FeedbackAnalysis>;

export function AnalyzeImportedAnswers(arg1:string):Promise<dialogue.ImportAnalysis>;

export function AppInfo():Promise<binding.AppInfo>;

export function ApplyUpdate():Promise<binding.UpdateState>;

export function ApproveDialogueCandidates(arg1:string,arg2:dialogue.ApprovalRequest):Promise<binding.ApprovalOutcome>;

export function ApproveImportCandidates(arg1:string,arg2:dialogue.FeedbackApproval):Promise<binding.ApprovalOutcome>;

export function ApproveImportDiff(arg1:string,arg2:dialogue.ImportApproval):Promise<binding.ApprovalOutcome>;

export function AskNextQuestion(arg1:string):Promise<boolean>;

export function BackupGenerations(arg1:string):Promise<Array<binding.BackupGenerationView>>;

export function BackupProject(arg1:string):Promise<string>;

export function CancelCodexSignIn():Promise<void>;

export function CancelRespondAIMessage():Promise<void>;

export function CancelUpdate():Promise<binding.UpdateState>;

export function ChangeHistory():Promise<Array<binding.ChangeHistoryView>>;

export function ChangeMemberRole(arg1:binding.MemberRequest):Promise<binding.MemberView>;

export function ChangeSummary():Promise<binding.ChangeSummaryView>;

export function CheckDocumentReservation(arg1:string):Promise<binding.ReservationCheckView>;

export function CheckForUpdate():Promise<binding.UpdateState>;

export function CheckPhaseDocumentReservation():Promise<binding.ReservationCheckView>;

export function CheckReservation(arg1:string):Promise<binding.ReservationCheckView>;

export function CheckSyncConnection(arg1:string,arg2:string):Promise<binding.SyncCheckView>;

export function ChooseBackupFile():Promise<string>;

export function ChooseFolder(arg1:string):Promise<string>;

export function ChooseImportDirectory():Promise<string>;

export function ChooseImportFile():Promise<string>;

export function ChooseIssueDestination(arg1:string):Promise<string>;

export function ChooseProgressReportDestination():Promise<string>;

export function ChooseProject(arg1:string):Promise<string>;

export function ChooseReturnDestination():Promise<string>;

export function ChooseReturnFile():Promise<string>;

export function ChooseUsageReportDestination():Promise<string>;

export function ClearUsageLimit():Promise<binding.UsageStatus>;

export function CloneSyncProject(arg1:binding.CloneSyncProjectRequest):Promise<binding.CloneSyncProjectView>;

export function CloseDialogueProject():Promise<void>;

export function CodexAccount(arg1:string):Promise<binding.SignInView>;

export function CodexPlanUsage(arg1:string):Promise<binding.PlanUsageView>;

export function CodexSignInState():Promise<binding.SignInView>;

export function CompleteSetup(arg1:binding.SetupRequest):Promise<void>;

export function ConfirmCheck(arg1:string):Promise<binding.ConfirmCheckView>;

export function ConfirmDocument(arg1:string,arg2:binding.WorkStart):Promise<binding.ConfirmResultView>;

export function CopyProgressReport(arg1:binding.ProgressReportRequest):Promise<string>;

export function CopyUsageReport(arg1:binding.UsageReportRequest):Promise<string>;

export function CorrectMemberAuthorID(arg1:string,arg2:string):Promise<binding.MemberView>;

export function CreateProject(arg1:binding.CreateProjectRequest):Promise<binding.ProjectSummary>;

export function CreateSyncMergeOpenIssue(arg1:binding.CreateSyncMergeOpenIssueRequest):Promise<binding.SyncMergeOpenIssueView>;

export function CurrentPermission():Promise<binding.PermissionView>;

export function Decisions():Promise<Array<binding.DecisionView>>;

export function DeferUpdate():Promise<binding.UpdateState>;

export function DeleteKey(arg1:string,arg2:string):Promise<void>;

export function DeletePreview(arg1:string):Promise<binding.DeletePreview>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSyncCredential(arg1:string):Promise<void>;

export function DiagnosticsPreview():Promise<applog.Diagnostic>;

export function DialogueCompleteness():Promise<binding.DialogueCompletenessView>;

export function DialogueSessions():Promise<Array<binding.DialogueSessionView>>;

export function DialogueUtterances(arg1:string):Promise<Array<binding.UtteranceView>>;

export function DisableRespondAI():Promise<binding.RespondAIDialogueView>;

export function DocumentChapters(arg1:string,arg2:number):Promise<Array<binding.DocumentChapterView>>;

export function DocumentDiff(arg1:string,arg2:number,arg3:number):Promise<Array<docgen.ChapterDiff>>;

export function DocumentVersions(arg1:string):Promise<Array<binding.DocumentVersionView>>;

export function DomainPresets():Promise<Array<binding.DomainPresetOption>>;

export function EditRequirement(arg1:binding.EditRequirementRequest):Promise<binding.RequirementView>;

export function EnableRespondAI(arg1:string,arg2:string,arg3:boolean):Promise<binding.RespondAIDialogueView>;

export function Evidence(arg1:string):Promise<binding.EvidenceView>;

export function EvidenceCitations(arg1:string):Promise<Array<projectstore.EvidenceCitation>>;

export function ExportDiagnostics():Promise<string>;

export function ExportDocuments(arg1:binding.ExportRequestView):Promise<docgen.ExportResult>;

export function FeedbackClassificationOptions():Promise<Array<binding.FeedbackClassificationOption>>;

export function FeedbackSummary(arg1:string,arg2:string):Promise<importer.FeedbackSummary>;

export function FinalizeAnswers(arg1:string):Promise<binding.RespondExportView>;

export function ForgetProject(arg1:string):Promise<void>;

export function GenerateDocument(arg1:string,arg2:boolean,arg3:binding.WorkStart):Promise<void>;

export function GenerateQuestionDrafts(arg1:Array<string>):Promise<binding.QuestionDraftsView>;

export function HandleOpenFile(arg1:string):Promise<void>;

export function IDRangeWarnings():Promise<Array<binding.IDRangeWarningView>>;

export function Impact(arg1:string):Promise<binding.ImpactView>;

export function ImportClipboardText(arg1:string,arg2:string):Promise<binding.ImportView>;

export function ImportContent(arg1:string):Promise<binding.ImportContentView>;

export function ImportDirectory(arg1:string,arg2:string):Promise<binding.ImportBatchView>;

export function ImportFile(arg1:string,arg2:string):Promise<binding.ImportView>;

export function ImportKinds():Promise<Array<binding.ImportKindOption>>;

export function ImportReturnFile(arg1:exchange.ImportConfirmation):Promise<binding.ImportResultView>;

export function Imports():Promise<Array<binding.ImportView>>;

export function IncorporateSync(arg1:Array<binding.SyncResolutionInput>):Promise<binding.SyncIncorporateView>;

export function InterruptDialogue():Promise<void>;

export function IntroShown():Promise<boolean>;

export function IssueQuestionnaire(arg1:binding.IssueDraftRequest,arg2:string):Promise<binding.IssueResultView>;

export function LocationWarning(arg1:string):Promise<string>;

export function Log():Promise<applog.Logger>;

export function MarkIntroShown():Promise<void>;

export function Members():Promise<Array<binding.MemberView>>;

export function MigratableProjects():Promise<Array<binding.MigratableProject>>;

export function MigrateProject(arg1:string):Promise<binding.ProjectSummary>;

export function MissingEvidenceRecords():Promise<Array<projectstore.MissingEvidenceRecord>>;

export function Models(arg1:string,arg2:string,arg3:string):Promise<binding.ModelList>;

export function MoveToBasicDesign():Promise<void>;

export function OpenDialogueProject(arg1:string):Promise<binding.DialogueOpenResult>;

export function OpenIssues():Promise<Array<binding.OpenIssueView>>;

export function OpenQuestionnaireFile(arg1:string,arg2:string):Promise<binding.RespondOpenResult>;

export function PaneWidths():Promise<binding.PaneWidthsView>;

export function PendingCandidates(arg1:string):Promise<dialogue.Extraction>;

export function PendingImportCandidates(arg1:string):Promise<dialogue.Extraction>;

export function PendingOpenFile():Promise<binding.OpenFileEvent>;

export function Perspectives():Promise<Array<binding.PerspectiveView>>;

export function PreviewBackup(arg1:string):Promise<binding.BackupPreview>;

export function PreviewImportAnalysis(arg1:string):Promise<dialogue.ImportSendPreview>;

export function PreviewQuestionnaireIssue(arg1:binding.IssueDraftRequest):Promise<binding.IssuePreviewView>;

export function PreviewSyncPublish():Promise<binding.SyncPublishPreviewView>;

export function PreviousRunIncomplete():Promise<boolean>;

export function ProgressReport(arg1:binding.ProgressReportRequest):Promise<binding.ProgressReportView>;

export function ProjectFolderNameFor(arg1:string):Promise<string>;

export function Projects():Promise<Array<binding.ProjectSummary>>;

export function PublishSync(arg1:boolean):Promise<binding.SyncPublishView>;

export function Questionnaires():Promise<Array<binding.QuestionnaireView>>;

export function ReattachSync():Promise<binding.SyncReattachView>;

export function RegisterKey(arg1:string,arg2:string,arg3:string):Promise<binding.VerifyResult>;

export function RegisterRespondAIKey(arg1:string,arg2:string,arg3:boolean):Promise<binding.VerifyResult>;

export function RegisterSyncCredential(arg1:binding.RegisterSyncCredentialRequest):Promise<binding.SyncCredentialView>;

export function ReissueQuestionnaire(arg1:string,arg2:string):Promise<binding.IssueResultView>;

export function ReleaseReservation(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ReleaseWindowLock(arg1:string,arg2:boolean):Promise<void>;

export function RemoveMember(arg1:string):Promise<void>;

export function RemovePerspective(arg1:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<binding.ProjectSummary>;

export function ReopenCodexSignInPage():Promise<void>;

export function Requirements():Promise<Array<binding.RequirementView>>;

export function Reservations():Promise<binding.ReservationsView>;

export function RespondAIAnswerDraft(arg1:string,arg2:string,arg3:string):Promise<binding.RespondAnswerDraftView>;

export function RespondAIDialogue():Promise<binding.RespondAIDialogueView>;

export function RespondAIProviders():Promise<Array<binding.ProviderOption>>;

export function RespondAIScope(arg1:string):Promise<binding.RespondAIScopeView>;

export function RespondProgress():Promise<binding.RespondProgressView>;

export function RestartApp():Promise<binding.UpdateState>;

export function RestoreBackup(arg1:string,arg2:string,arg3:boolean):Promise<binding.ProjectSummary>;

export function ResumeDialogueSession(arg1:string):Promise<dialogue.ResumeContext>;

export function RevertRequirement(arg1:string,arg2:string,arg3:binding.WorkStart):Promise<binding.RequirementView>;

export function Roster():Promise<Array<binding.StakeholderView>>;

export function SaveAnswer(arg1:binding.AnswerInput):Promise<binding.RespondProgressView>;

export function SaveProgressReport(arg1:binding.ProgressReportRequest,arg2:string):Promise<string>;

export function SaveProviderConfig(arg1:binding.UpdateProviderRequest):Promise<void>;

export function SaveUsageReport(arg1:binding.UsageReportRequest,arg2:string):Promise<string>;

export function ScaleStatus():Promise<Array<binding.ScaleWarning>>;

export function ScanImportDirectory(arg1:string):Promise<binding.ImportScanView>;

export function SearchDialogueUtterances(arg1:string,arg2:string,arg3:string):Promise<binding.UtteranceSearchView>;

export function SendAnswer(arg1:string,arg2:string):Promise<string>;

export function SendRespondAIMessage(arg1:string):Promise<binding.RespondAIDialogueView>;

export function SetAITimeouts(arg1:number,arg2:number):Promise<void>;

export function SetDisplayName(arg1:string):Promise<void>;

export function SetDomainPresets(arg1:string,arg2:Array<string>):Promise<void>;

export function SetFeedbackClassification(arg1:string,arg2:string):Promise<importer.Meta>;

export function SetPaneWidths(arg1:number,arg2:number):Promise<void>;

export function SetSyncRemote(arg1:binding.SetSyncRemoteRequest):Promise<binding.SyncRemoteView>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUsageLimit(arg1:binding.UsageLimitRequest):Promise<binding.UsageStatus>;

export function SettingsView():Promise<binding.SettingsView>;

export function SetupState():Promise<binding.SetupState>;

export function SignOutCodex(arg1:string):Promise<void>;

export function SignOutRespondAI():Promise<binding.RespondAIDialogueView>;

export function StartCodexSignIn(arg1:string):Promise<binding.SignInView>;

export function StartDialogueSession():Promise<binding.DialogueSessionView>;

export function StartRespondAISignIn(arg1:boolean):Promise<binding.SignInView>;

export function StartWork(arg1:string,arg2:string,arg3:boolean):Promise<binding.ReservationView>;

export function StartupMode():Promise<binding.StartupMode>;

export function SuspendDialogue(arg1:string):Promise<void>;

export function SyncCredentialView(arg1:string):Promise<binding.SyncCredentialView>;

export function SyncKindOptions():Promise<Array<binding.SyncKindOption>>;

export function SyncLog():Promise<binding.SyncLogView>;

export function SyncMergeOptions():Promise<Array<binding.SyncChoiceOption>>;

export function SyncRemote():Promise<binding.SyncRemoteView>;

export function SyncStatus():Promise<binding.SyncStatusView>;

export function TakeOverOwner(arg1:boolean):Promise<binding.MemberView>;

export function Theme():Promise<string>;

export function TokenUsage(arg1:binding.TokenUsageRequest):Promise<binding.TokenUsageView>;

export function UpdatePerspective(arg1:binding.PerspectiveRequest):Promise<binding.PerspectiveView>;

export function UpdateStakeholder(arg1:binding.StakeholderRequest):Promise<binding.StakeholderView>;

export function UpdateState():Promise<binding.UpdateState>;

export function UsageDashboard(arg1:binding.UsageReportRequest):Promise<binding.UsageDashboardView>;

export function UsageStatusNow():Promise<binding.UsageStatus>;

export function ValidateReturnFile(arg1:string):Promise<binding.ImportReviewView>;

export function VerifyDocument(arg1:string,arg2:number):Promise<docgen.VerifyResult>;

export function VerifyKey(arg1:string,arg2:string):Promise<binding.VerifyResult>;

export function WindowLocks():Promise<Array<binding.WindowLockView>>;

export function WorkModeOptions():Promise<Array<binding.WorkModeOption>>;

export function WorkflowGuide():Promise<binding.GuideView>;
