/*
 * 画面の型（対話系・文書承認系・一覧管理系・パネル/バナー系・ウィザード系）に対応する共通コンポーネント。
 * 画面個別に同種のUIを再実装しない（見た目と振る舞いを 1 か所で直せるように）。
 *
 *   対話系            … AppShell + Utterance
 *   一覧・管理系      … AppShell + DataList
 *   文書・承認系      … AppShell + DocumentWorkspace（+ DiffAddition）
 *   ウィザード・回答系 … Wizard（AppShell を使わない = 統制表示を出さない）
 *   パネル・バナー系  … Banner（恒久状態）/ Toast（一過性の操作結果）
 */
export {AppShell} from './AppShell'
export type {Completeness, RecordCounts, TokenUsage} from './AppShell'
export {Banner} from './Banner'
export {Button} from './Button'
export type {ButtonVariant} from './Button'
export {ChangeSummaryPanel} from './ChangeSummaryPanel'
export {CandidateEvidence, lacksEvidence, noEvidenceReason} from './CandidateEvidence'
export type {EvidenceSource} from './CandidateEvidence'
export {Chip} from './Chip'
export {CodexSignIn} from './CodexSignIn'
export {PlanUsage} from './PlanUsage'
export {IDRangeNotice} from './IDRangeNotice'
export {DataList} from './DataList'
export type {Column, Row} from './DataList'
export {DocumentWorkspace, DiffAddition} from './DocumentWorkspace'
export {EmptyState} from './EmptyState'
export {FlyingCard, prefersReducedMotion} from './FlyingCard'
export {ScreenHint, useGuideHint} from './GuideHint'
export {GuideStrip} from './GuideStrip'
export type {CycleStep, GuideStripProps} from './GuideStrip'
export {CYCLE_STEPS} from './GuideStrip'
export type {EmptyStateProps} from './EmptyState'
export {defaultPeriod, formatCount, formatLocal, formatRatio} from './format'
export {errorText} from './errorText'
export {useFollowLatest} from './useFollowLatest'
export {Markdown} from './Markdown'
export {Overlay} from './Overlay'
export {MergePanel} from './MergePanel'
export type {MergeChoice} from './MergePanel'
export type {Action} from './DocumentWorkspace'
export {Toast} from './Toast'
export {Tooltip} from './Tooltip'
export {UpdateNotice} from './UpdateNotice'
export {ScaleNotice} from './ScaleNotice'
export {SkeletonCard} from './SkeletonCard'
export {PreviousRunNotice} from './PreviousRunNotice'
export {SyncMergePanel} from './SyncMergePanel'
export {UsageNotice} from './UsageNotice'
export {Utterance} from './Utterance'
export type {Speaker} from './Utterance'
export {STATE_TONES} from './state'
export type {StateTone} from './state'
export {Wizard, useWizardPane, PANE_MIN_WORK_PX, PANE_UNAVAILABLE_REASON} from './Wizard'
export {WorkflowOverview} from './WorkflowOverview'
export type {WorkflowStage} from './WorkflowOverview'
export {WorkStartDialog} from './WorkStartDialog'
